name: numberbonds
description: Maths numberbonds

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

# dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter
flutter:
  uses-material-design: true
